import Blog from '../../Images/ProjectImages/Blog.png'

export const projectData = {
    blog:{
        name:'Blog',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
    blogapi:{
        name:'Blog API',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
    blogcontroller:{
        name:'Blog Controller',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
    modernresponsive:{
        name:'Modern Responsive Website',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
    membersforum:{
        name:'Members Forum',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
    reduxshopping:{
        name:'Redux Amiibo Shopping',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
    reduxbattleship:{
        name:'Redux Battleship',
        description:`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
        tags:[
            'HTML',
            'CSS',
            'Javascript',
            'Express',
            'JWT Auth',
            'React',
        ],
        appSite:'#',
        codeSite:'#',
        imgSrc:Blog,
    },
}